

env:
  AZURE_WEBAPP_NAME: ticketing    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root

name: deploy-auth
on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t ozerdur/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ozerdur/auth
      
      # - uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      #   ticketing is the cluster name
      # - run: doctl kubernetes cluster kubeconfig save ticketing 
      # - run: kubectl rollout restart deployment auth-depl
      

     # - name: 'Deploy to Azure WebApp'
     #   uses: azure/webapps-deploy@v2
     #   with:
     #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
     #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
     #     package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}      

